### PR TITLE
Revised Legal & Mark Up

### PR DESCRIPTION
**Pull request by bydefault**

### CODE REVIEW

**Comment by sebasoga** [comment]
@bydefault there seems to be a conflict that prevents this be merged. Let me know if I can help.

**Comment by bydefault** [comment]
Styling for these ToS. Let's use local device fonts on both iOS and Android to ensure a faster load:

**As far as text sizing:**
H1: 28pt
H2: 22pt
P: 16pt

**Comment by apeace** [comment]
@bydefault LGTM. cc: @buritica for styling

One note: if you can wrap the date like this, I put a script in the README that can update the date automatically :D

```
Replace:
<p>Last Updated: March 31, 2016</p>

With:
<p>Last Updated: <span id="date">March 31, 2016</span></p>
```

**Comment by buritica** [comment]
this needs some more styling love, it's expanding beyond the width of the screen so content is not being wrapped. we could merge this and send another pr fixing that part

**Comment by buritica** [comment]
oh, this is just structure. i'll add styles tom

**Pull request merged**
